### ISSUE TITLE
Pretrained weights on Stanford datasets

### ISSUE THREAD

**Issue by SIYUAN9446** [z-fabian/HUMUS-Net#11]
Thanks for sharing the code of such interesting work.

Could you please also provide the pre-trained weights on Stanford 2D FSE and Stanford 3D FSE datasets?

Thanks in advance!

**Comment by z-fabian** [comment]
Hi @SIYUAN9446,

Thanks for reaching out. We uploaded the Stanford checkpoints and you can find them [here](https://github.com/z-fabian/HUMUS-Net/tree/master#pre-trained-models). 

Please keep in mind that there is no train/test split defined on these datasets, so we trained 3 models from scratch on different random train-val splits and averaged the results in the paper. The uploaded checkpoints correspond to setting `train_val_seed` to `0` and `train_val_split` to `0.8`.

**Comment by SIYUAN9446** [comment]
Hi @z-fabian，

Thanks a lot for your reply.
