### ISSUE TITLE
Training on single-coil data

### ISSUE THREAD

**Issue by ChongWang1024** [z-fabian/HUMUS-Net#9]
Hi, thanks for sharing the codes and the interesting paper!
I would like to know whether this model can be used for single-coil data reconstruction (e.g., fastMRI single-coil knee dataset), since in the paper the model is designed for multi-coil data.
Thanks in advance.

**Comment by z-fabian** [comment]
Hi @ChongWang1024,
Thanks for your interest in our work. Even though HUMUS-Net was primarily designed and tested on multi-coil data, we see no reason why our hybrid denoiser would not perform well on single-coil data. To work with single-coil data, our network would need to be modified by (1) removing the sensitivity map estimator (sens maps are given with single-coil data) and (2) replacing the coil reduce/expand operations with simple 2D Fourier/inverse-Fourier transforms. 
I hope this helps!

**Comment by ChongWang1024** [comment]
Hi @z-fabian ,
Thanks so much! That helps a lot!
